# `cptac.utils` Reactome search function demos

This notebook goes over two  functions I've added to `cptac.utils`. They both query the [Reactome Content Service API](https://reactome.org/dev/content-service) for information related to pathway membership.

In [1]:
import cptac.utils as ut

## `search_reactome_pathways_with_proteins`

This function takes a single protein or a list of proteins as input, and returns a dataframe telling you all pathways that contain each protein.

In [2]:
df = ut.search_reactome_pathways_with_proteins("BRCA1")
df.head()

      id                                            pathway     pathway_id
0  BRCA1                                   Meiotic synapsis  R-HSA-1221632
1  BRCA1  SUMOylation of DNA damage response and repair ...  R-HSA-3108214
2  BRCA1          HDR through Single Strand Annealing (SSA)  R-HSA-5685938
3  BRCA1         HDR through Homologous Recombination (HRR)  R-HSA-5685942
4  BRCA1                               Metalloprotease DUBs  R-HSA-5689901

In [3]:
df = ut.search_reactome_pathways_with_proteins(["PTEN", "PIK3CA"])
df.head()

     id                                      pathway     pathway_id
0  PTEN     Synthesis of PIPs at the plasma membrane  R-HSA-1660499
1  PTEN      Synthesis of IP3 and IP4 in the cytosol  R-HSA-1855204
2  PTEN  Negative regulation of the PI3K/AKT network   R-HSA-199418
3  PTEN                     Downstream TCR signaling   R-HSA-202424
4  PTEN               TP53 Regulates Metabolic Genes  R-HSA-5628897

In [4]:
df.tail()

        id                                            pathway     pathway_id
55  PIK3CA               Activated NTRK3 signals through PI3K  R-HSA-9603381
56  PIK3CA                      Signaling by ERBB2 KD Mutants  R-HSA-9664565
57  PIK3CA                     Signaling by ERBB2 ECD mutants  R-HSA-9665348
58  PIK3CA  Signaling by PDGFRA transmembrane, juxtamembra...  R-HSA-9673767
59  PIK3CA   Signaling by PDGFRA extracellular domain mutants  R-HSA-9673770

If you query for an identifier for which no information is found, a warning is issued. You can silence these by setting the `quiet` parameter to `True`.

In [5]:
df = ut.search_reactome_pathways_with_proteins(["PTEN", "yatahey"])
df.head()

cptac warning: The query for 'yatahey' returned HTTP 404 (not found). You may have mistyped the gene/protein ID or the resource name. The server gave the following message: ['No pathways found for UniProt:yatahey'] (/home/caleb/anaconda3/envs/dev/lib/python3.7/site-packages/ipykernel_launcher.py, line 1)

     id                                      pathway     pathway_id
0  PTEN     Synthesis of PIPs at the plasma membrane  R-HSA-1660499
1  PTEN      Synthesis of IP3 and IP4 in the cytosol  R-HSA-1855204
2  PTEN  Negative regulation of the PI3K/AKT network   R-HSA-199418
3  PTEN                     Downstream TCR signaling   R-HSA-202424
4  PTEN               TP53 Regulates Metabolic Genes  R-HSA-5628897

In [6]:
df = ut.search_reactome_pathways_with_proteins(["PTEN", "yatahey"], quiet=True)
df.head()

     id                                      pathway     pathway_id
0  PTEN     Synthesis of PIPs at the plasma membrane  R-HSA-1660499
1  PTEN      Synthesis of IP3 and IP4 in the cytosol  R-HSA-1855204
2  PTEN  Negative regulation of the PI3K/AKT network   R-HSA-199418
3  PTEN                     Downstream TCR signaling   R-HSA-202424
4  PTEN               TP53 Regulates Metabolic Genes  R-HSA-5628897

# `search_reactome_proteins_in_pathways`

This function takes a single Reactome pathway identifier or a list of them, and tells you all proteins and gene products contained in it or them.

In [7]:
df = ut.search_reactome_proteins_in_pathways("R-HSA-8935690")
df.head()

      pathway_id member
0  R-HSA-8935690   ALPI
1  R-HSA-8935690  AMY1A
2  R-HSA-8935690  AMY1B
3  R-HSA-8935690  AMY2A
4  R-HSA-8935690  AMY2B

In [8]:
df = ut.search_reactome_proteins_in_pathways(["R-HSA-8935690", "R-HSA-418346"])
df.head()

      pathway_id member
0  R-HSA-8935690   ALPI
1  R-HSA-8935690  AMY1A
2  R-HSA-8935690  AMY1B
3  R-HSA-8935690  AMY2A
4  R-HSA-8935690  AMY2B

In [9]:
df.tail()

       pathway_id member
104  R-HSA-418346    SRI
105  R-HSA-418346  STIM1
106  R-HSA-418346  TRPC3
107  R-HSA-418346  TRPC6
108  R-HSA-418346  TRPC7

Like the previous function, it issues a warning when identifiers are not found, and those warnings can be repressed with the `quiet` parameter.

In [10]:
df = ut.search_reactome_proteins_in_pathways(["R-HSA-8935690", "yatahey"])
df.head()

cptac warning: The query for 'yatahey' found no results. You may have mistyped the pathway ID. (/home/caleb/anaconda3/envs/dev/lib/python3.7/site-packages/ipykernel_launcher.py, line 1)

      pathway_id member
0  R-HSA-8935690   ALPI
1  R-HSA-8935690  AMY1A
2  R-HSA-8935690  AMY1B
3  R-HSA-8935690  AMY2A
4  R-HSA-8935690  AMY2B

In [11]:
df = ut.search_reactome_proteins_in_pathways(["R-HSA-8935690", "yatahey"], quiet=True)
df.head()

      pathway_id member
0  R-HSA-8935690   ALPI
1  R-HSA-8935690  AMY1A
2  R-HSA-8935690  AMY1B
3  R-HSA-8935690  AMY2A
4  R-HSA-8935690  AMY2B