# Pancancer enrichment analysis step 2: Find enriched pathways
# Version 2: Using Reactome's Analysis Service API for enrichment analysis

## Setup

In [1]:
import cptac
import cptac.utils as ut
import pandas as pd
import numpy as np
import os
import datetime

In [2]:
TIME_START = datetime.datetime.now().strftime('%Y%m%d_%H%M%S')

STEP1_DIR = "step1_outputs"
STEP1_FILE = "tumor_change_20200529_195104_10000_perm.tsv"
STEP1_FILE_PATH = os.path.join(STEP1_DIR, STEP1_FILE)

STEP2_DIR = "step2_outputs_reactome"
STEP2_FILE = f"urls_{TIME_START}_from_{STEP1_FILE.rsplit('.', maxsplit=1)[0]}.tsv"
STEP2_FILE_PATH = os.path.join(STEP2_DIR, STEP2_FILE)

if not os.path.isdir(STEP2_DIR):
    os.mkdir(STEP2_DIR)

## Prepare data

In [3]:
# Read in the file from step 1
data = pd.read_csv(STEP1_FILE_PATH, sep='\t', index_col=0)

# The ranked enrichment analysis service wants ranking scores
# where "bigger is better", such as expression values or
# t scores. We are ranking by adjusted p-values, where smaller
# is better. So, we'll create a column of (1 - adj_p) to use
# for ranking.
data = data.assign(one_minus_adj_p=1 - data["adj_p"])

# Make a column where all increases are +1 and all decreases 
# are -1, because these are ratioed abundances, so we can't 
# compare magnitudes between genes--we can only compare whether 
# there was a change, and whether it was positive or negative
data = data.assign(simplified_change=data["change"])

data.loc[data["change"] > 0, "simplified_change"] = 1
data.loc[data["change"] < 0, "simplified_change"] = -1
data.loc[data["change"] == 0, "simplified_change"] = 0

In [4]:
data.head()

,cancer_type,protein,change,P_val,adj_p,reject_null,protein_str,one_minus_adj_p,simplified_change
0,ccrcc,"('A1BG', 'NP_570602.2')",0.282928,0.0000,0.00000,True,A1BG,1.00000,1.0
1,ccrcc,"('A1CF', 'NP_620310.1')",-0.551358,0.0000,0.00000,True,A1CF,1.00000,-1.0
2,ccrcc,"('A2M', 'NP_000005.2')",0.595512,0.0000,0.00000,True,A2M,1.00000,1.0
3,ccrcc,"('A4GALT', 'NP_001304967.1')",0.479410,0.1735,0.21431,False,A4GALT,0.78569,1.0
4,ccrcc,"('AAAS', 'NP_056480.1')",0.173579,0.0000,0.00000,True,AAAS,1.00000,1.0

## Run enrichment analysis

In [5]:
# For each cancer, find enriched pathways based on p value for differential expression   
all_enrichments = pd.DataFrame()

for cancer_type in data["cancer_type"].unique():
    
    ranked_data = data.loc[data["cancer_type"] == cancer_type, ["protein_str", "one_minus_adj_p"]].\
        set_index("protein_str").\
        rename(columns={"one_minus_adj_p": f"{cancer_type}_one_minus_adj_p"})

    unneeded_token, cancer_enriched = ut.reactome_enrichment_analysis(
        analysis_type="ranked", 
        data=ranked_data, 
        sort_by="ENTITIES_FDR", 
        ascending=True,
        include_high_level_diagrams=False, 
        include_interactors=False)
    
    # Record the cancer type and rename the pathway id column
    cancer_enriched = cancer_enriched.\
        assign(cancer_type=cancer_type).\
        rename(columns={"stId": "pathway_id"})
    
    # Append to the overall dataframe
    all_enrichments = all_enrichments.append(cancer_enriched)

In [6]:
all_enrichments.head()

,pathway_id,name,entities_ratio,entities_pValue,entities_fdr,entities_found,entities_total,cancer_type
0,R-HSA-3108214,SUMOylation of DNA damage response and repair ...,0.005581,0.045443,0.84264,81,81,ccrcc
1,R-HSA-4551638,SUMOylation of chromatin organization proteins,0.004272,0.071045,0.84264,62,62,ccrcc
2,R-HSA-4570464,SUMOylation of RNA binding proteins,0.003514,0.093002,0.84264,51,51,ccrcc
3,R-HSA-4615885,SUMOylation of DNA replication proteins,0.003445,0.095357,0.84264,50,50,ccrcc
4,R-HSA-159234,Transport of Mature mRNAs Derived from Intronl...,0.003238,0.102846,0.84264,47,47,ccrcc

In [7]:
all_enrichments.sort_values(by="entities_fdr")

,pathway_id,name,entities_ratio,entities_pValue,entities_fdr,entities_found,entities_total,cancer_type
0,R-HSA-6798695,Neutrophil degranulation,0.033072,6.216916e-12,1.500142e-08,434,480,colon
1,R-HSA-6791226,Major pathway of rRNA processing in the nucleo...,0.013022,2.825057e-07,1.376497e-04,181,189,colon
2,R-HSA-72203,Processing of Capped Intron-Containing Pre-mRNA,0.017638,2.855803e-07,1.376497e-04,233,256,colon
3,R-HSA-72163,mRNA Splicing - Major Pathway,0.012746,9.094579e-07,3.656021e-04,175,185,colon
4,R-HSA-72172,mRNA Splicing,0.013504,1.078818e-05,2.891233e-03,177,196,colon
9,R-HSA-927802,Nonsense-Mediated Decay (NMD),0.008543,1.856749e-04,2.580882e-02,114,124,colon
5,R-HSA-72689,Formation of a pool of free 40S subunits,0.007303,1.239514e-04,2.580882e-02,101,106,colon
6,R-HSA-72706,GTP hydrolysis and joining of the 60S ribosoma...,0.008268,1.212962e-04,2.580882e-02,112,120,colon
7,R-HSA-1799339,SRP-dependent cotranslational protein targetin...,0.008199,1.324252e-04,2.580882e-02,111,119,colon
8,R-HSA-156827,L13a-mediated translational silencing of Cerul...,0.008268,1.792866e-04,2.580882e-02,111,120,colon
10,R-HSA-975957,Nonsense Mediated Decay (NMD) enhanced by the ...,0.008543,1.856749e-04,2.580882e-02,114,124,colon
11,R-HSA-72613,Eukaryotic Translation Initiation,0.008957,1.611030e-04,2.580882e-02,119,130,colon
12,R-HSA-72737,Cap-dependent Translation Initiation,0.008957,1.611030e-04,2.580882e-02,119,130,colon
13,R-HSA-162906,HIV Infection,0.018052,1.926031e-04,2.580882e-02,217,262,colon
14,R-HSA-877300,Interferon gamma signaling,0.017225,2.694769e-04,3.072037e-02,207,250,colon
15,R-HSA-975956,Nonsense Mediated Decay (NMD) independent of t...,0.006959,2.916028e-04,3.178470e-02,95,101,colon
16,R-HSA-68882,Mitotic Anaphase,0.017087,3.119587e-04,3.244371e-02,205,248,colon
17,R-HSA-2555396,Mitotic Metaphase and Anaphase,0.017156,3.793775e-04,3.793775e-02,205,249,colon
24,R-HSA-9010553,Regulation of expression of SLITs and ROBOs,0.012609,4.407327e-04,4.181614e-02,156,183,colon
23,R-HSA-72312,rRNA processing,0.016880,5.063380e-04,4.181614e-02,201,245,colon
21,R-HSA-5419276,Mitochondrial translation termination,0.006477,5.430667e-04,4.181614e-02,88,94,colon
22,R-HSA-1236974,ER-Phagosome pathway,0.011368,5.332158e-04,4.181614e-02,142,165,colon
19,R-HSA-72202,Transport of Mature Transcript to Cytoplasm,0.006201,5.165473e-04,4.181614e-02,85,90,colon
18,R-HSA-1236977,Endosomal/Vacuolar pathway,0.005650,4.565422e-04,4.181614e-02,79,82,colon
20,R-HSA-5389840,Mitochondrial translation elongation,0.006477,5.430667e-04,4.181614e-02,88,94,colon
25,R-HSA-5368287,Mitochondrial translation,0.007028,5.889043e-04,4.296296e-02,94,102,colon
26,R-HSA-376176,Signaling by ROBO receptors,0.016191,6.137566e-04,4.296296e-02,193,235,colon
27,R-HSA-2132295,MHC class II antigen presentation,0.010197,8.080648e-04,5.090808e-02,128,148,colon
28,R-HSA-1236975,Antigen processing-Cross presentation,0.012884,7.858005e-04,5.090808e-02,157,187,colon
29,R-HSA-983170,"Antigen Presentation: Folding, assembly and pe...",0.007028,8.619877e-04,5.171926e-02,93,102,colon
...,...,...,...,...,...,...,...,...
2196,R-HSA-375280,Amine ligand-binding receptors,0.006063,1.000000e+00,1.000000e+00,12,88,ccrcc
2197,R-HSA-9635486,Infection with Mycobacterium tuberculosis,0.009301,1.000000e+00,1.000000e+00,24,135,ccrcc
2198,R-HSA-1222499,Latent infection - Other responses of Mtb to p...,0.004961,1.000000e+00,1.000000e+00,1,72,ccrcc
2173,R-HSA-375280,Amine ligand-binding receptors,0.006063,1.000000e+00,1.000000e+00,10,88,ovarian
2171,R-HSA-1222499,Latent infection - Other responses of Mtb to p...,0.004961,1.000000e+00,1.000000e+00,1,72,gbm
2192,R-HSA-420499,Class C/3 (Metabotropic glutamate/pheromone re...,0.006408,1.000000e+00,1.000000e+00,12,93,ccrcc
2181,R-HSA-5690714,CD22 mediated BCR regulation,0.004961,1.000000e+00,1.000000e+00,8,72,ccrcc
2180,R-HSA-173623,Classical antibody-mediated complement activation,0.006683,1.000000e+00,1.000000e+00,11,97,ccrcc
2179,R-HSA-418555,G alpha (s) signalling events,0.041684,1.000000e+00,1.000000e+00,88,605,ccrcc
2179,R-HSA-420499,Class C/3 (Metabotropic glutamate/pheromone re...,0.006408,1.000000e+00,1.000000e+00,14,93,lscc
2180,R-HSA-8956319,Nucleobase catabolism,0.009577,1.000000e+00,1.000000e+00,33,139,lscc
2181,R-HSA-211897,Cytochrome P450 - arranged by substrate type,0.012746,1.000000e+00,1.000000e+00,41,185,lscc
2182,R-HSA-2142753,Arachidonic acid metabolism,0.011437,1.000000e+00,1.000000e+00,50,166,lscc
2183,R-HSA-9609646,HCMV Infection,0.018603,1.000000e+00,1.000000e+00,101,270,lscc
2184,R-HSA-373076,Class A/1 (Rhodopsin-like receptors),0.031831,1.000000e+00,1.000000e+00,143,462,lscc
2185,R-HSA-9018677,Biosynthesis of DHA-derived SPMs,0.006132,1.000000e+00,1.000000e+00,12,89,lscc
2186,R-HSA-375280,Amine ligand-binding receptors,0.006063,1.000000e+00,1.000000e+00,12,88,lscc
2187,R-HSA-9635486,Infection with Mycobacterium tuberculosis,0.009301,1.000000e+00,1.000000e+00,24,135,lscc
2188,R-HSA-1222499,Latent infection - Other responses of Mtb to p...,0.004961,1.000000e+00,1.000000e+00,1,72,lscc
2169,R-HSA-9662851,Anti-inflammatory response favouring Leishmani...,0.020463,1.000000e+00,1.000000e+00,106,297,ccrcc
2171,R-HSA-9664323,FCGR3A-mediated IL10 synthesis,0.009715,1.000000e+00,1.000000e+00,38,141,ccrcc
2172,R-HSA-2173782,Binding and Uptake of Ligands by Scavenger Rec...,0.011506,1.000000e+00,1.000000e+00,43,167,ccrcc
2173,R-HSA-2871809,FCERI mediated Ca+2 mobilization,0.008888,1.000000e+00,1.000000e+00,32,129,ccrcc
2174,R-HSA-166663,Initial triggering of complement,0.008268,1.000000e+00,1.000000e+00,27,120,ccrcc
2175,R-HSA-166786,Creation of C4 and C2 activators,0.007648,1.000000e+00,1.000000e+00,19,111,ccrcc
2176,R-HSA-2730905,Role of LAT2/NTAL/LAB on calcium mobilization,0.007372,1.000000e+00,1.000000e+00,18,107,ccrcc
2177,R-HSA-2029481,FCGR activation,0.007097,1.000000e+00,1.000000e+00,17,103,ccrcc
2178,R-HSA-2168880,Scavenging of heme from plasma,0.007303,1.000000e+00,1.000000e+00,17,106,ccrcc
2166,R-HSA-9664433,Leishmania parasite growth and survival,0.020463,1.000000e+00,1.000000e+00,113,297,hnscc
2174,R-HSA-1222499,Latent infection - Other responses of Mtb to p...,0.004961,1.000000e+00,1.000000e+00,1,72,ovarian

## Summarize enrichment results from all cancers

In [8]:
# Make a table with a list of all pathways, and:
# - The number of cancer types for which that cancer type is enriched
# - The average of the adjusted p-values for that pathway
# - The average overlap proportion for that pathway
enrichment_summary = all_enrichments[["pathway_id", "name"]].drop_duplicates(keep="first")

times_enriched = enrichment_summary["pathway_id"].apply(
    lambda x: all_enrichments[all_enrichments["pathway_id"] == x].shape[0])

avg_fdr = enrichment_summary["pathway_id"].apply(
    lambda x: all_enrichments.loc[all_enrichments["pathway_id"] == x, "entities_fdr"].mean())

avg_overlap_props = enrichment_summary["pathway_id"].apply(
    lambda x: all_enrichments.loc[all_enrichments["pathway_id"] == x, "entities_ratio"].mean())

enrichment_summary = enrichment_summary.assign(
    times_enriched=times_enriched,
    pathway_avg_fdr=avg_fdr,
    pathway_avg_overlap=avg_overlap_props)

enrichment_summary = enrichment_summary.sort_values(
    by=["times_enriched", "pathway_avg_fdr"],
    ascending=[False, True])

enrichment_summary = enrichment_summary.reset_index(drop=True)

In [9]:
enrichment_summary.head()

,pathway_id,name,times_enriched,pathway_avg_fdr,pathway_avg_overlap
0,R-HSA-6798695,Neutrophil degranulation,8,0.587721,0.033072
1,R-HSA-6791226,Major pathway of rRNA processing in the nucleo...,8,0.725419,0.013022
2,R-HSA-72203,Processing of Capped Intron-Containing Pre-mRNA,8,0.725419,0.017638
3,R-HSA-72163,mRNA Splicing - Major Pathway,8,0.725447,0.012746
4,R-HSA-72172,mRNA Splicing,8,0.725763,0.013504

## Visualize pathways with expression change

In [10]:
# Submit the differential expression data for each cancer type to the analysis service, and get the tokens
# The data we'd submitted previously were the p values for the differential expression, but that's not what
# we want to visualize; we want to see whether the expression was up or down.
diff_expr_tokens = {}

for cancer_type in data["cancer_type"].unique():

    # Select data for that cancer type
    # Exclude samples where not reject_null
    omics = data.loc[(data["cancer_type"] == cancer_type) & data["reject_null"], 
                     ["protein_str", "simplified_change"]].\
        set_index("protein_str").\
        rename(columns={"simplified_change": f"{cancer_type}_simp_change"})

    analysis_token, unneeded_df = ut.reactome_enrichment_analysis(
        analysis_type="ranked", 
        data=omics, 
        sort_by="ENTITIES_FDR", 
        ascending=True,
        include_high_level_diagrams=True, 
        include_interactors=False)
    
    diff_expr_tokens[cancer_type] = analysis_token

In [11]:
# Select pathways to get URLs for
to_viz = enrichment_summary.iloc[0:10, :]

# Get URLs
id_list = []
cancer_type_list = []
expr_list = []
url_list = []

for idx in to_viz.index:
    pathway_id = to_viz.loc[idx, "pathway_id"]
    
    for cancer_type in data["cancer_type"].unique():
         
        # Get the URL
        expr_vals, url = ut.reactome_pathway_overlay(
            pathway=pathway_id,
            analysis_token=diff_expr_tokens[cancer_type],
            open_browser=False)
        
        id_list.append(pathway_id)
        cancer_type_list.append(cancer_type)
        expr_list.append(expr_vals[0])
        url_list.append(url)

urls_df = pd.DataFrame({
        "pathway_id": id_list,
        "cancer_type": cancer_type_list,
        "mean_expr": expr_list,
        "url": url_list})

In [12]:
# Join in the enrichment summary table
urls_df = urls_df.merge(
    enrichment_summary,
    how="left",
    left_on="pathway_id",
    right_on="pathway_id",
    validate="many_to_one")

urls_df

,pathway_id,cancer_type,mean_expr,url,name,times_enriched,pathway_avg_fdr,pathway_avg_overlap
0,R-HSA-6798695,ccrcc,0.233503,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Neutrophil degranulation,8,0.587721,0.033072
1,R-HSA-6798695,colon,-0.134831,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Neutrophil degranulation,8,0.587721,0.033072
2,R-HSA-6798695,endometrial,0.288515,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Neutrophil degranulation,8,0.587721,0.033072
3,R-HSA-6798695,gbm,0.166227,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Neutrophil degranulation,8,0.587721,0.033072
4,R-HSA-6798695,hnscc,0.133159,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Neutrophil degranulation,8,0.587721,0.033072
5,R-HSA-6798695,lscc,-0.407595,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Neutrophil degranulation,8,0.587721,0.033072
6,R-HSA-6798695,luad,-0.410000,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Neutrophil degranulation,8,0.587721,0.033072
7,R-HSA-6798695,ovarian,-0.303754,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Neutrophil degranulation,8,0.587721,0.033072
8,R-HSA-6791226,ccrcc,0.699422,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Major pathway of rRNA processing in the nucleo...,8,0.725419,0.013022
9,R-HSA-6791226,colon,0.771429,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Major pathway of rRNA processing in the nucleo...,8,0.725419,0.013022
10,R-HSA-6791226,endometrial,0.759494,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Major pathway of rRNA processing in the nucleo...,8,0.725419,0.013022
11,R-HSA-6791226,gbm,0.795181,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Major pathway of rRNA processing in the nucleo...,8,0.725419,0.013022
12,R-HSA-6791226,hnscc,0.479290,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Major pathway of rRNA processing in the nucleo...,8,0.725419,0.013022
13,R-HSA-6791226,lscc,0.680000,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Major pathway of rRNA processing in the nucleo...,8,0.725419,0.013022
14,R-HSA-6791226,luad,0.680000,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Major pathway of rRNA processing in the nucleo...,8,0.725419,0.013022
15,R-HSA-6791226,ovarian,0.760000,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Major pathway of rRNA processing in the nucleo...,8,0.725419,0.013022
16,R-HSA-72203,ccrcc,0.549296,https://reactome.org/PathwayBrowser/#/R-HSA-72...,Processing of Capped Intron-Containing Pre-mRNA,8,0.725419,0.017638
17,R-HSA-72203,colon,0.741935,https://reactome.org/PathwayBrowser/#/R-HSA-72...,Processing of Capped Intron-Containing Pre-mRNA,8,0.725419,0.017638
18,R-HSA-72203,endometrial,0.152542,https://reactome.org/PathwayBrowser/#/R-HSA-72...,Processing of Capped Intron-Containing Pre-mRNA,8,0.725419,0.017638
19,R-HSA-72203,gbm,0.742222,https://reactome.org/PathwayBrowser/#/R-HSA-72...,Processing of Capped Intron-Containing Pre-mRNA,8,0.725419,0.017638
20,R-HSA-72203,hnscc,0.663551,https://reactome.org/PathwayBrowser/#/R-HSA-72...,Processing of Capped Intron-Containing Pre-mRNA,8,0.725419,0.017638
21,R-HSA-72203,lscc,0.686636,https://reactome.org/PathwayBrowser/#/R-HSA-72...,Processing of Capped Intron-Containing Pre-mRNA,8,0.725419,0.017638
22,R-HSA-72203,luad,0.547368,https://reactome.org/PathwayBrowser/#/R-HSA-72...,Processing of Capped Intron-Containing Pre-mRNA,8,0.725419,0.017638
23,R-HSA-72203,ovarian,0.723077,https://reactome.org/PathwayBrowser/#/R-HSA-72...,Processing of Capped Intron-Containing Pre-mRNA,8,0.725419,0.017638
24,R-HSA-72163,ccrcc,0.500000,https://reactome.org/PathwayBrowser/#/R-HSA-72...,mRNA Splicing - Major Pathway,8,0.725447,0.012746
25,R-HSA-72163,colon,0.731707,https://reactome.org/PathwayBrowser/#/R-HSA-72...,mRNA Splicing - Major Pathway,8,0.725447,0.012746
26,R-HSA-72163,endometrial,0.205882,https://reactome.org/PathwayBrowser/#/R-HSA-72...,mRNA Splicing - Major Pathway,8,0.725447,0.012746
27,R-HSA-72163,gbm,0.750000,https://reactome.org/PathwayBrowser/#/R-HSA-72...,mRNA Splicing - Major Pathway,8,0.725447,0.012746
28,R-HSA-72163,hnscc,0.664596,https://reactome.org/PathwayBrowser/#/R-HSA-72...,mRNA Splicing - Major Pathway,8,0.725447,0.012746
29,R-HSA-72163,lscc,0.672727,https://reactome.org/PathwayBrowser/#/R-HSA-72...,mRNA Splicing - Major Pathway,8,0.725447,0.012746
...,...,...,...,...,...,...,...,...
50,R-HSA-927802,endometrial,0.626168,https://reactome.org/PathwayBrowser/#/R-HSA-92...,Nonsense-Mediated Decay (NMD),8,0.728628,0.008543
51,R-HSA-927802,gbm,0.771429,https://reactome.org/PathwayBrowser/#/R-HSA-92...,Nonsense-Mediated Decay (NMD),8,0.728628,0.008543
52,R-HSA-927802,hnscc,0.233645,https://reactome.org/PathwayBrowser/#/R-HSA-92...,Nonsense-Mediated Decay (NMD),8,0.728628,0.008543
53,R-HSA-927802,lscc,0.711538,https://reactome.org/PathwayBrowser/#/R-HSA-92...,Nonsense-Mediated Decay (NMD),8,0.728628,0.008543
54,R-HSA-927802,luad,0.709091,https://reactome.org/PathwayBrowser/#/R-HSA-92...,Nonsense-Mediated Decay (NMD),8,0.728628,0.008543
55,R-HSA-927802,ovarian,0.877551,https://reactome.org/PathwayBrowser/#/R-HSA-92...,Nonsense-Mediated Decay (NMD),8,0.728628,0.008543
56,R-HSA-975957,ccrcc,0.611111,https://reactome.org/PathwayBrowser/#/R-HSA-97...,Nonsense Mediated Decay (NMD) enhanced by the ...,8,0.728628,0.008543
57,R-HSA-975957,colon,0.814815,https://reactome.org/PathwayBrowser/#/R-HSA-97...,Nonsense Mediated Decay (NMD) enhanced by the ...,8,0.728628,0.008543
58,R-HSA-975957,endometrial,0.626168,https://reactome.org/PathwayBrowser/#/R-HSA-97...,Nonsense Mediated Decay (NMD) enhanced by the ...,8,0.728628,0.008543
59,R-HSA-975957,gbm,0.771429,https://reactome.org/PathwayBrowser/#/R-HSA-97...,Nonsense Mediated Decay (NMD) enhanced by the ...,8,0.728628,0.008543
60,R-HSA-975957,hnscc,0.233645,https://reactome.org/PathwayBrowser/#/R-HSA-97...,Nonsense Mediated Decay (NMD) enhanced by the ...,8,0.728628,0.008543
61,R-HSA-975957,lscc,0.711538,https://reactome.org/PathwayBrowser/#/R-HSA-97...,Nonsense Mediated Decay (NMD) enhanced by the ...,8,0.728628,0.008543
62,R-HSA-975957,luad,0.709091,https://reactome.org/PathwayBrowser/#/R-HSA-97...,Nonsense Mediated Decay (NMD) enhanced by the ...,8,0.728628,0.008543
63,R-HSA-975957,ovarian,0.877551,https://reactome.org/PathwayBrowser/#/R-HSA-97...,Nonsense Mediated Decay (NMD) enhanced by the ...,8,0.728628,0.008543
64,R-HSA-72706,ccrcc,0.641509,https://reactome.org/PathwayBrowser/#/R-HSA-72...,GTP hydrolysis and joining of the 60S ribosoma...,8,0.728628,0.008268
65,R-HSA-72706,colon,0.834862,https://reactome.org/PathwayBrowser/#/R-HSA-72...,GTP hydrolysis and joining of the 60S ribosoma...,8,0.728628,0.008268
66,R-HSA-72706,endometrial,0.716981,https://reactome.org/PathwayBrowser/#/R-HSA-72...,GTP hydrolysis and joining of the 60S ribosoma...,8,0.728628,0.008268
67,R-HSA-72706,gbm,0.862745,https://reactome.org/PathwayBrowser/#/R-HSA-72...,GTP hydrolysis and joining of the 60S ribosoma...,8,0.728628,0.008268
68,R-HSA-72706,hnscc,0.292929,https://reactome.org/PathwayBrowser/#/R-HSA-72...,GTP hydrolysis and joining of the 60S ribosoma...,8,0.728628,0.008268
69,R-HSA-72706,lscc,0.669903,https://reactome.org/PathwayBrowser/#/R-HSA-72...,GTP hydrolysis and joining of the 60S ribosoma...,8,0.728628,0.008268
70,R-HSA-72706,luad,0.676190,https://reactome.org/PathwayBrowser/#/R-HSA-72...,GTP hydrolysis and joining of the 60S ribosoma...,8,0.728628,0.008268
71,R-HSA-72706,ovarian,0.849057,https://reactome.org/PathwayBrowser/#/R-HSA-72...,GTP hydrolysis and joining of the 60S ribosoma...,8,0.728628,0.008268
72,R-HSA-156827,ccrcc,0.657143,https://reactome.org/PathwayBrowser/#/R-HSA-15...,L13a-mediated translational silencing of Cerul...,8,0.728628,0.008268
73,R-HSA-156827,colon,0.851852,https://reactome.org/PathwayBrowser/#/R-HSA-15...,L13a-mediated translational silencing of Cerul...,8,0.728628,0.008268
74,R-HSA-156827,endometrial,0.698113,https://reactome.org/PathwayBrowser/#/R-HSA-15...,L13a-mediated translational silencing of Cerul...,8,0.728628,0.008268
75,R-HSA-156827,gbm,0.861386,https://reactome.org/PathwayBrowser/#/R-HSA-15...,L13a-mediated translational silencing of Cerul...,8,0.728628,0.008268
76,R-HSA-156827,hnscc,0.285714,https://reactome.org/PathwayBrowser/#/R-HSA-15...,L13a-mediated translational silencing of Cerul...,8,0.728628,0.008268
77,R-HSA-156827,lscc,0.666667,https://reactome.org/PathwayBrowser/#/R-HSA-15...,L13a-mediated translational silencing of Cerul...,8,0.728628,0.008268
78,R-HSA-156827,luad,0.692308,https://reactome.org/PathwayBrowser/#/R-HSA-15...,L13a-mediated translational silencing of Cerul...,8,0.728628,0.008268
79,R-HSA-156827,ovarian,0.866667,https://reactome.org/PathwayBrowser/#/R-HSA-15...,L13a-mediated translational silencing of Cerul...,8,0.728628,0.008268

In [13]:
# Join in the original enrichment data for each pathway and cancer type
urls_df = urls_df.merge(
    all_enrichments,
    how="left",
    left_on=["pathway_id", "name", "cancer_type"],
    right_on=["pathway_id", "name", "cancer_type"])

urls_df

,pathway_id,cancer_type,mean_expr,url,name,times_enriched,pathway_avg_fdr,pathway_avg_overlap,entities_ratio,entities_pValue,entities_fdr,entities_found,entities_total
0,R-HSA-6798695,ccrcc,0.233503,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Neutrophil degranulation,8,0.587721,0.033072,0.033072,3.467008e-03,8.426404e-01,448,480
1,R-HSA-6798695,colon,-0.134831,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Neutrophil degranulation,8,0.587721,0.033072,0.033072,6.216916e-12,1.500142e-08,434,480
2,R-HSA-6798695,endometrial,0.288515,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Neutrophil degranulation,8,0.587721,0.033072,0.033072,1.403496e-03,8.219205e-01,450,480
3,R-HSA-6798695,gbm,0.166227,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Neutrophil degranulation,8,0.587721,0.033072,0.033072,2.129677e-03,8.037977e-01,448,480
4,R-HSA-6798695,hnscc,0.133159,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Neutrophil degranulation,8,0.587721,0.033072,0.033072,3.649260e-03,8.329209e-01,462,480
5,R-HSA-6798695,lscc,-0.407595,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Neutrophil degranulation,8,0.587721,0.033072,0.033072,1.637558e-03,8.726502e-01,443,480
6,R-HSA-6798695,luad,-0.410000,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Neutrophil degranulation,8,0.587721,0.033072,0.033072,1.800932e-04,4.412282e-01,441,480
7,R-HSA-6798695,ovarian,-0.303754,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Neutrophil degranulation,8,0.587721,0.033072,0.033072,3.532076e-05,8.660650e-02,441,480
8,R-HSA-6791226,ccrcc,0.699422,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Major pathway of rRNA processing in the nucleo...,8,0.725419,0.013022,0.013022,3.132093e-02,8.426404e-01,179,189
9,R-HSA-6791226,colon,0.771429,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Major pathway of rRNA processing in the nucleo...,8,0.725419,0.013022,0.013022,2.825057e-07,1.376497e-04,181,189
10,R-HSA-6791226,endometrial,0.759494,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Major pathway of rRNA processing in the nucleo...,8,0.725419,0.013022,0.013022,1.984718e-02,8.219205e-01,180,189
11,R-HSA-6791226,gbm,0.795181,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Major pathway of rRNA processing in the nucleo...,8,0.725419,0.013022,0.013022,1.421603e-02,8.037977e-01,182,189
12,R-HSA-6791226,hnscc,0.479290,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Major pathway of rRNA processing in the nucleo...,8,0.725419,0.013022,0.013022,5.698112e-02,8.329209e-01,181,189
13,R-HSA-6791226,lscc,0.680000,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Major pathway of rRNA processing in the nucleo...,8,0.725419,0.013022,0.013022,1.017413e-02,8.726502e-01,181,189
14,R-HSA-6791226,luad,0.680000,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Major pathway of rRNA processing in the nucleo...,8,0.725419,0.013022,0.013022,2.770984e-03,8.489584e-01,181,189
15,R-HSA-6791226,ovarian,0.760000,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Major pathway of rRNA processing in the nucleo...,8,0.725419,0.013022,0.013022,1.590139e-03,7.803251e-01,180,189
16,R-HSA-72203,ccrcc,0.549296,https://reactome.org/PathwayBrowser/#/R-HSA-72...,Processing of Capped Intron-Containing Pre-mRNA,8,0.725419,0.017638,0.017638,1.862319e-02,8.426404e-01,241,256
17,R-HSA-72203,colon,0.741935,https://reactome.org/PathwayBrowser/#/R-HSA-72...,Processing of Capped Intron-Containing Pre-mRNA,8,0.725419,0.017638,0.017638,2.855803e-07,1.376497e-04,233,256
18,R-HSA-72203,endometrial,0.152542,https://reactome.org/PathwayBrowser/#/R-HSA-72...,Processing of Capped Intron-Containing Pre-mRNA,8,0.725419,0.017638,0.017638,9.292015e-03,8.219205e-01,243,256
19,R-HSA-72203,gbm,0.742222,https://reactome.org/PathwayBrowser/#/R-HSA-72...,Processing of Capped Intron-Containing Pre-mRNA,8,0.725419,0.017638,0.017638,1.398083e-02,8.037977e-01,241,256
20,R-HSA-72203,hnscc,0.663551,https://reactome.org/PathwayBrowser/#/R-HSA-72...,Processing of Capped Intron-Containing Pre-mRNA,8,0.725419,0.017638,0.017638,7.432083e-02,8.329209e-01,239,256
21,R-HSA-72203,lscc,0.686636,https://reactome.org/PathwayBrowser/#/R-HSA-72...,Processing of Capped Intron-Containing Pre-mRNA,8,0.725419,0.017638,0.017638,8.766714e-02,8.726502e-01,225,256
22,R-HSA-72203,luad,0.547368,https://reactome.org/PathwayBrowser/#/R-HSA-72...,Processing of Capped Intron-Containing Pre-mRNA,8,0.725419,0.017638,0.017638,2.671711e-01,8.489584e-01,207,256
23,R-HSA-72203,ovarian,0.723077,https://reactome.org/PathwayBrowser/#/R-HSA-72...,Processing of Capped Intron-Containing Pre-mRNA,8,0.725419,0.017638,0.017638,1.740219e-03,7.803251e-01,236,256
24,R-HSA-72163,ccrcc,0.500000,https://reactome.org/PathwayBrowser/#/R-HSA-72...,mRNA Splicing - Major Pathway,8,0.725447,0.012746,0.012746,2.383523e-02,8.426404e-01,177,185
25,R-HSA-72163,colon,0.731707,https://reactome.org/PathwayBrowser/#/R-HSA-72...,mRNA Splicing - Major Pathway,8,0.725447,0.012746,0.012746,9.094579e-07,3.656021e-04,175,185
26,R-HSA-72163,endometrial,0.205882,https://reactome.org/PathwayBrowser/#/R-HSA-72...,mRNA Splicing - Major Pathway,8,0.725447,0.012746,0.012746,9.902183e-03,8.219205e-01,180,185
27,R-HSA-72163,gbm,0.750000,https://reactome.org/PathwayBrowser/#/R-HSA-72...,mRNA Splicing - Major Pathway,8,0.725447,0.012746,0.012746,1.555753e-02,8.037977e-01,178,185
28,R-HSA-72163,hnscc,0.664596,https://reactome.org/PathwayBrowser/#/R-HSA-72...,mRNA Splicing - Major Pathway,8,0.725447,0.012746,0.012746,6.057434e-02,8.329209e-01,177,185
29,R-HSA-72163,lscc,0.672727,https://reactome.org/PathwayBrowser/#/R-HSA-72...,mRNA Splicing - Major Pathway,8,0.725447,0.012746,0.012746,5.786661e-02,8.726502e-01,168,185
...,...,...,...,...,...,...,...,...,...,...,...,...,...
50,R-HSA-927802,endometrial,0.626168,https://reactome.org/PathwayBrowser/#/R-HSA-92...,Nonsense-Mediated Decay (NMD),8,0.728628,0.008543,0.008543,8.755204e-02,8.219205e-01,115,124
51,R-HSA-927802,gbm,0.771429,https://reactome.org/PathwayBrowser/#/R-HSA-92...,Nonsense-Mediated Decay (NMD),8,0.728628,0.008543,0.008543,9.008047e-02,8.037977e-01,115,124
52,R-HSA-927802,hnscc,0.233645,https://reactome.org/PathwayBrowser/#/R-HSA-92...,Nonsense-Mediated Decay (NMD),8,0.728628,0.008543,0.008543,1.570822e-01,8.329209e-01,116,124
53,R-HSA-927802,lscc,0.711538,https://reactome.org/PathwayBrowser/#/R-HSA-92...,Nonsense-Mediated Decay (NMD),8,0.728628,0.008543,0.008543,9.466540e-02,8.726502e-01,113,124
54,R-HSA-927802,luad,0.709091,https://reactome.org/PathwayBrowser/#/R-HSA-92...,Nonsense-Mediated Decay (NMD),8,0.728628,0.008543,0.008543,4.687555e-02,8.489584e-01,113,124
55,R-HSA-927802,ovarian,0.877551,https://reactome.org/PathwayBrowser/#/R-HSA-92...,Nonsense-Mediated Decay (NMD),8,0.728628,0.008543,0.008543,1.904926e-02,7.803251e-01,115,124
56,R-HSA-975957,ccrcc,0.611111,https://reactome.org/PathwayBrowser/#/R-HSA-97...,Nonsense Mediated Decay (NMD) enhanced by the ...,8,0.728628,0.008543,0.008543,1.036529e-01,8.426404e-01,115,124
57,R-HSA-975957,colon,0.814815,https://reactome.org/PathwayBrowser/#/R-HSA-97...,Nonsense Mediated Decay (NMD) enhanced by the ...,8,0.728628,0.008543,0.008543,1.856749e-04,2.580882e-02,114,124
58,R-HSA-975957,endometrial,0.626168,https://reactome.org/PathwayBrowser/#/R-HSA-97...,Nonsense Mediated Decay (NMD) enhanced by the ...,8,0.728628,0.008543,0.008543,8.755204e-02,8.219205e-01,115,124
59,R-HSA-975957,gbm,0.771429,https://reactome.org/PathwayBrowser/#/R-HSA-97...,Nonsense Mediated Decay (NMD) enhanced by the ...,8,0.728628,0.008543,0.008543,9.008047e-02,8.037977e-01,115,124
60,R-HSA-975957,hnscc,0.233645,https://reactome.org/PathwayBrowser/#/R-HSA-97...,Nonsense Mediated Decay (NMD) enhanced by the ...,8,0.728628,0.008543,0.008543,1.570822e-01,8.329209e-01,116,124
61,R-HSA-975957,lscc,0.711538,https://reactome.org/PathwayBrowser/#/R-HSA-97...,Nonsense Mediated Decay (NMD) enhanced by the ...,8,0.728628,0.008543,0.008543,9.466540e-02,8.726502e-01,113,124
62,R-HSA-975957,luad,0.709091,https://reactome.org/PathwayBrowser/#/R-HSA-97...,Nonsense Mediated Decay (NMD) enhanced by the ...,8,0.728628,0.008543,0.008543,4.687555e-02,8.489584e-01,113,124
63,R-HSA-975957,ovarian,0.877551,https://reactome.org/PathwayBrowser/#/R-HSA-97...,Nonsense Mediated Decay (NMD) enhanced by the ...,8,0.728628,0.008543,0.008543,1.904926e-02,7.803251e-01,115,124
64,R-HSA-72706,ccrcc,0.641509,https://reactome.org/PathwayBrowser/#/R-HSA-72...,GTP hydrolysis and joining of the 60S ribosoma...,8,0.728628,0.008268,0.008268,1.129414e-01,8.426404e-01,111,120
65,R-HSA-72706,colon,0.834862,https://reactome.org/PathwayBrowser/#/R-HSA-72...,GTP hydrolysis and joining of the 60S ribosoma...,8,0.728628,0.008268,0.008268,1.212962e-04,2.580882e-02,112,120
66,R-HSA-72706,endometrial,0.716981,https://reactome.org/PathwayBrowser/#/R-HSA-72...,GTP hydrolysis and joining of the 60S ribosoma...,8,0.728628,0.008268,0.008268,9.604753e-02,8.219205e-01,111,120
67,R-HSA-72706,gbm,0.862745,https://reactome.org/PathwayBrowser/#/R-HSA-72...,GTP hydrolysis and joining of the 60S ribosoma...,8,0.728628,0.008268,0.008268,8.282869e-02,8.037977e-01,112,120
68,R-HSA-72706,hnscc,0.292929,https://reactome.org/PathwayBrowser/#/R-HSA-72...,GTP hydrolysis and joining of the 60S ribosoma...,8,0.728628,0.008268,0.008268,1.675023e-01,8.329209e-01,112,120
69,R-HSA-72706,lscc,0.669903,https://reactome.org/PathwayBrowser/#/R-HSA-72...,GTP hydrolysis and joining of the 60S ribosoma...,8,0.728628,0.008268,0.008268,1.237171e-01,8.726502e-01,108,120
70,R-HSA-72706,luad,0.676190,https://reactome.org/PathwayBrowser/#/R-HSA-72...,GTP hydrolysis and joining of the 60S ribosoma...,8,0.728628,0.008268,0.008268,6.511218e-02,8.489584e-01,108,120
71,R-HSA-72706,ovarian,0.849057,https://reactome.org/PathwayBrowser/#/R-HSA-72...,GTP hydrolysis and joining of the 60S ribosoma...,8,0.728628,0.008268,0.008268,1.748934e-02,7.803251e-01,112,120
72,R-HSA-156827,ccrcc,0.657143,https://reactome.org/PathwayBrowser/#/R-HSA-15...,L13a-mediated translational silencing of Cerul...,8,0.728628,0.008268,0.008268,1.327433e-01,8.426404e-01,110,120
73,R-HSA-156827,colon,0.851852,https://reactome.org/PathwayBrowser/#/R-HSA-15...,L13a-mediated translational silencing of Cerul...,8,0.728628,0.008268,0.008268,1.792866e-04,2.580882e-02,111,120
74,R-HSA-156827,endometrial,0.698113,https://reactome.org/PathwayBrowser/#/R-HSA-15...,L13a-mediated translational silencing of Cerul...,8,0.728628,0.008268,0.008268,1.137660e-01,8.219205e-01,110,120
75,R-HSA-156827,gbm,0.861386,https://reactome.org/PathwayBrowser/#/R-HSA-15...,L13a-mediated translational silencing of Cerul...,8,0.728628,0.008268,0.008268,9.870829e-02,8.037977e-01,111,120
76,R-HSA-156827,hnscc,0.285714,https://reactome.org/PathwayBrowser/#/R-HSA-15...,L13a-mediated translational silencing of Cerul...,8,0.728628,0.008268,0.008268,1.928606e-01,8.329209e-01,111,120
77,R-HSA-156827,lscc,0.666667,https://reactome.org/PathwayBrowser/#/R-HSA-15...,L13a-mediated translational silencing of Cerul...,8,0.728628,0.008268,0.008268,1.450742e-01,8.726502e-01,107,120
78,R-HSA-156827,luad,0.692308,https://reactome.org/PathwayBrowser/#/R-HSA-15...,L13a-mediated translational silencing of Cerul...,8,0.728628,0.008268,0.008268,7.870713e-02,8.489584e-01,107,120
79,R-HSA-156827,ovarian,0.866667,https://reactome.org/PathwayBrowser/#/R-HSA-15...,L13a-mediated translational silencing of Cerul...,8,0.728628,0.008268,0.008268,2.221054e-02,7.803251e-01,111,120

In [14]:
# Print the dataframe in such a way that the links are clickable
urls_df.style.format('<a href="{0}">{0}</a>', subset="url")

In [15]:
# import webbrowser
# for url in urls_df["url"][0:8]:
#     webbrowser.open(url)

In [16]:
# Save the results
urls_df.to_csv(STEP2_FILE_PATH, sep='\t')