# Looking at neutrophil stuff

## Setup

In [1]:
import cptac
import cptac.utils as ut
import pandas as pd
import numpy as np
import os
import datetime

## CXCL* proteins

According to section 3 of [Neutrophils in Cancer: Two Sides of the Same Coin (2015)](https://www.hindawi.com/journals/jir/2015/983698/), CXCL* chemokines help recruit neutrophils, especially CXCL8.

In [2]:
STEP1_DIR = "step1_outputs"
STEP1_FILE = "tumor_change_20200529_195104_10000_perm.tsv"
STEP1_FILE_PATH = os.path.join(STEP1_DIR, STEP1_FILE)

# Read in the file from step 1
data = pd.read_csv(STEP1_FILE_PATH, sep='\t', index_col=0)

# The ranked enrichment analysis service wants ranking scores
# where "bigger is better", such as expression values or
# t scores. We are ranking by adjusted p-values, where smaller
# is better. So, we'll create a column of (1 - adj_p) to use
# for ranking.
data = data.assign(one_minus_adj_p=1 - data["adj_p"])

# Make a column where all increases are +1 and all decreases 
# are -1, because these are ratioed abundances, so we can't 
# compare magnitudes between genes--we can only compare whether 
# there was a change, and whether it was positive or negative
data = data.assign(simplified_change=data["change"])

data.loc[data["change"] > 0, "simplified_change"] = 1
data.loc[data["change"] < 0, "simplified_change"] = -1
data.loc[data["change"] == 0, "simplified_change"] = 0

In [3]:
sel = data[data["protein_str"].str.startswith("CXCL")][["cancer_type", "protein_str", "adj_p", "simplified_change"]]

In [4]:
sel

       cancer_type protein_str     adj_p  simplified_change
2438         ccrcc      CXCL10  0.058316                1.0
2439         ccrcc      CXCL12  0.000000               -1.0
2440         ccrcc      CXCL14  0.000000               -1.0
2441         ccrcc      CXCL16  0.000000                1.0
2442         ccrcc       CXCL5  0.113626                1.0
2443         ccrcc       CXCL8  0.143739                1.0
2444         ccrcc       CXCL9  0.000188                1.0
13372        colon       CXCL1  0.003636                1.0
13373        colon      CXCL10  0.620817                1.0
13374        colon      CXCL12  0.000000               -1.0
13375        colon      CXCL13  0.169014               -1.0
13376        colon      CXCL14  0.002045                1.0
13377        colon       CXCL5  0.226778                1.0
13378        colon       CXCL8  0.000000                1.0
21995  endometrial       CXCL1  0.030312                1.0
21996  endometrial      CXCL10  0.000000                1.0
21997  endometrial      CXCL12  0.000000               -1.0
21998  endometrial      CXCL13  0.988897               -1.0
21999  endometrial      CXCL14  0.002207                1.0
22000  endometrial      CXCL16  0.129091               -1.0
22001  endometrial      CXCL17  0.000000                1.0
22002  endometrial       CXCL3  0.057285                1.0
22003  endometrial       CXCL5  0.011579                1.0
22004  endometrial       CXCL6  0.218009                1.0
22005  endometrial       CXCL8  0.000887                1.0
22006  endometrial       CXCL9  0.352439                1.0
33014          gbm       CXCL1  0.455119                1.0
33015          gbm      CXCL10  0.146651                1.0
33016          gbm      CXCL12  0.555167                1.0
33017          gbm      CXCL13  0.583342                1.0
...            ...         ...       ...                ...
44318        hnscc      CXCL16  0.074815               -1.0
44319        hnscc      CXCL17  0.000000               -1.0
44320        hnscc       CXCL5  0.001223                1.0
44321        hnscc       CXCL8  0.000000                1.0
44322        hnscc       CXCL9  0.002207                1.0
55961         lscc       CXCL1  0.000000                1.0
55962         lscc      CXCL10  0.386932                1.0
55963         lscc      CXCL12  0.000000               -1.0
55964         lscc      CXCL13  0.000000                1.0
55965         lscc      CXCL14  0.000000                1.0
55966         lscc      CXCL16  0.000000               -1.0
55967         lscc      CXCL17  0.000000               -1.0
55968         lscc       CXCL5  0.959005                1.0
55969         lscc       CXCL6  0.076938                1.0
55970         lscc       CXCL8  0.000000                1.0
55971         lscc       CXCL9  0.010413                1.0
67134         luad       CXCL1  0.230444                1.0
67135         luad      CXCL10  0.997267               -1.0
67136         luad      CXCL12  0.000000               -1.0
67137         luad      CXCL13  0.000368                1.0
67138         luad      CXCL14  0.000188                1.0
67139         luad      CXCL16  0.000000               -1.0
67140         luad      CXCL17  0.974757                1.0
67141         luad       CXCL5  0.270461               -1.0
67142         luad       CXCL8  0.004416                1.0
77739      ovarian      CXCL10  0.677138               -1.0
77740      ovarian      CXCL12  0.000000               -1.0
77741      ovarian      CXCL13  0.655607               -1.0
77742      ovarian      CXCL14  0.000000               -1.0
77743      ovarian      CXCL16  0.244311               -1.0

[70 rows x 4 columns]

In [9]:
data[data["protein_str"].str.startswith("MMP")][["cancer_type", "protein_str", "adj_p", "simplified_change"]]

       cancer_type protein_str     adj_p  simplified_change
5916         ccrcc       MMP12  0.015175                1.0
5917         ccrcc       MMP14  0.000000                1.0
5918         ccrcc       MMP15  0.000000                1.0
5919         ccrcc       MMP19  0.002689                1.0
5920         ccrcc        MMP2  0.000000               -1.0
5921         ccrcc     MMP24OS  0.000000               -1.0
5922         ccrcc       MMP28  0.000368               -1.0
5923         ccrcc        MMP3  0.650909               -1.0
5924         ccrcc        MMP7  0.000000               -1.0
5925         ccrcc        MMP8  0.000000                1.0
5926         ccrcc        MMP9  0.000000                1.0
15777        colon        MMP1  0.000000                1.0
15778        colon       MMP11  0.000000                1.0
15779        colon       MMP12  0.096180                1.0
15780        colon       MMP14  0.000000                1.0
15781        colon        MMP2  0.000188                1.0
15782        colon      MMP23B  0.000887               -1.0
15783        colon       MMP28  0.000000               -1.0
15784        colon        MMP3  0.212631                1.0
15785        colon        MMP7  0.312435                1.0
15786        colon        MMP8  0.000887                1.0
15787        colon        MMP9  0.000000                1.0
25314  endometrial        MMP1  0.565215                1.0
25315  endometrial       MMP10  0.012158               -1.0
25316  endometrial       MMP11  0.296059               -1.0
25317  endometrial       MMP12  0.000000                1.0
25318  endometrial       MMP14  0.000188                1.0
25319  endometrial       MMP15  0.000000                1.0
25320  endometrial       MMP19  0.000000               -1.0
25321  endometrial        MMP2  0.000000               -1.0
...            ...         ...       ...                ...
59352         lscc        MMP8  0.023723               -1.0
59353         lscc        MMP9  0.000717               -1.0
70348         luad        MMP1  0.000000                1.0
70349         luad       MMP10  0.001718               -1.0
70350         luad       MMP11  0.008949                1.0
70351         luad       MMP12  0.000000                1.0
70352         luad       MMP14  0.000000                1.0
70353         luad       MMP15  0.484680               -1.0
70354         luad       MMP19  0.008207               -1.0
70355         luad        MMP2  0.120743               -1.0
70356         luad      MMP23B  0.000000               -1.0
70357         luad       MMP24  0.001056                1.0
70358         luad     MMP24OS  0.000000               -1.0
70359         luad       MMP25  0.000188               -1.0
70360         luad       MMP28  0.000000               -1.0
70361         luad        MMP7  0.000000                1.0
70362         luad        MMP8  0.000000               -1.0
70363         luad        MMP9  0.000000               -1.0
80949      ovarian        MMP1  0.968186               -1.0
80950      ovarian       MMP10  0.058316               -1.0
80951      ovarian       MMP11  0.887354                1.0
80952      ovarian       MMP12  0.031672               -1.0
80953      ovarian       MMP14  0.516205                1.0
80954      ovarian       MMP15  0.256660                1.0
80955      ovarian       MMP19  0.000000               -1.0
80956      ovarian        MMP2  0.155884               -1.0
80957      ovarian      MMP23B  0.036368               -1.0
80958      ovarian        MMP7  0.420221                1.0
80959      ovarian        MMP8  0.000000               -1.0
80960      ovarian        MMP9  0.000000               -1.0

[109 rows x 4 columns]